[query]
bucket = 'prototype-zero'
time_format = "%Y-%m-%dT%H:%M:%SZ"
delta_time_start = [0, 0, 0, 0]                          # days, hours, minutes, seconds
delta_time_end = [0, 24, 0, 0]                           # days, hours, minutes, seconds
tz_offset = -8                                           # hours
columns_to_drop = ["result", "table", "_start", "_stop"]
column_key = "_field"                                    # key to use for column axis
sort_by = ["_time", "_field"]                            # columns to sort by
aggregate_function = "last"                              # aggregation function to use
aggregate_window = "1s"

# Filter to apply to the data, uses regex
# filter = 'r["id"] =~ /.*/' # Include all data that has an id key
filter = 'r["_measurement"] == "liner_heater"' # Include all data with _measurement == "liner_heater"
